### ISSUE TITLE
Why do serialization errors not throw?

### ISSUE THREAD

**Issue by kelunik** [jeremeamia/super_closure#101]
https://github.com/jeremeamia/super_closure/blob/f57f48cb328552f6af7c4ad61f51b35a4237b546/src/SerializableClosure.php#L114-L120

The above says it can't throw, but [my small test shows it's possible](https://3v4l.org/mQ5E0). Am I missing something?

**Comment by jeremeamia** [comment]
Possibly a legacy thing. Look at your output for [5.3.0](https://3v4l.org/mQ5E0#v530).
Also, this is a weird note in the [PHP docs](http://php.net/manual/en/serializable.serialize.php#refsect1-serializable.serialize-errors)
It's possible that it could safely be removed. :man_shrugging:

**Comment by kelunik** [comment]
Even there, PHP just chains an internal exception internally. https://3v4l.org/ZaLYA

Would you accept a PR or would that be a BC break? If it is considered a BC break we'll just go ahead and use a throwing error handler.

**Comment by jeremeamia** [comment]
This software is no longer maintained. Consider using [opis/closure](https://github.com/opis/closure) instead.

**Comment by kelunik** [comment]
[We already do](https://github.com/amphp/parallel-functions/blob/master/composer.json), thanks!
