### ISSUE TITLE
Arrow functions serialization

### ISSUE THREAD

**Issue by arokettu** [jeremeamia/super_closure#112]
It would be nice to have it at 7.4 final release

https://wiki.php.net/rfc/arrow_functions

```php
$serializer = new SuperClosure\Serializer();
$b = 5;
$test = fn($a) => $a * 5;
$c = $serializer->serialize($test);
```

Expected: serialized closure
Actual result: `ClosureAnalysisException: The closure was not found within the abstract syntax tree`

**Comment by sandfoxme** [comment]
Ok, it might be an insanity due to implicit use() :(

**Comment by b1rdex** [comment]
Any thoughts on this? Php 7.4 is live, just stumbled upon this issue using PHP-DI compiled container (https://github.com/PHP-DI/PHP-DI/issues/706).

**Comment by arokettu** [comment]
@b1rdex If I remember correctly, the fix for PHP-DI is trivial and I even managed to make it work sort of, but super_closure is not only a PHP-DI backend and it should serialize variables in use() statement. This was the problem when I got stuck

**Comment by b1rdex** [comment]
@arokettu could you please share the fix for arrow functions without use()? It'd be better than nothing.

**Comment by arokettu** [comment]
@b1rdex just replace this check

https://github.com/jeremeamia/super_closure/blob/5707d5821b30b9a07acfb4d76949784aaa0e9ce9/src/Analyzer/Visitor/ClosureLocatorVisitor.php#L72

with ``$node instanceof ClosureNode || $node instanceof ArrowFunctionNode`` and it will work except for $uses warning

**Comment by arokettu** [comment]
This is a full file with the change, sorry, don't have it in git

https://gist.github.com/arokettu/aac75ac809577b83b16d2583587c5af6

**Comment by jeremeamia** [comment]
This software is no longer maintained. Consider using [opis/closure](https://github.com/opis/closure) instead. I believe they have added short function support.

**Comment by b1rdex** [comment]
@jeremeamia yes you're right. Here is the implementation: https://github.com/opis/closure/commit/86fc51fce952567570e0629a22981665be02e7ff
