### ISSUE TITLE
erialization of closure failed: The closure was not found within the abstract syntax tree.'

### ISSUE THREAD

**Issue by zwfec** [jeremeamia/super_closure#113]
php environment: php7.3.12

PHP User Notice 'yii\base\ErrorException' with message 'Serialization of closure failed: The closure was not found within the abstract syntax tree.'
​
 echo $x ?? '111';

super_closure don't suport ?? syntax 

change: 
opcache.enable_cli=1
to: 
opcache.enable_cli=0

**Comment by GrahamCampbell** [comment]
Thanks for the report. Are you saying turning off opcache on the cli fixed things?

**Comment by jeremeamia** [comment]
This software is no longer maintained. Consider using [opis/closure][https://github.com/opis/closure] instead.
