### ISSUE TITLE
Magic invocation breaks pass by-ref

### ISSUE THREAD

**Issue by Ceiu** [jeremeamia/super_closure#14]
When invoking the closure through the __invoke magic method, values which should be passed by-ref are, instead, passed by-value.

Test code:
```php
  use Jeremeamia\SuperClosure\SerializableClosure;

  $closure = function(&$ref = null) {
    $ref = "new value!";
  };

  $sclosure = new SerializableClosure($closure);


  $var1 = null;
  $closure($var1);

  $var2 = null;
  $sclosure($var2);

  var_dump($var1, $var2);
```

Outputs:
```
string 'new value!' (length=10)
null
```

Expected:
```
string 'new value!' (length=10)
string 'new value!' (length=10)
```

-----

Now, I'm not so sure about previous versions, but a patch I've applied to SerializableClosure.php that works for 5.4 is as follows:
```php
    public function __invoke(&$arg0 = null, &$arg1 = null, &$arg2 = null, &$arg3 = null, &$arg4 = null, &$arg5 = null, &$arg6 = null, &$arg7 = null, &$arg8 = null, &$arg9 = null)
    {
      $stack = debug_backtrace(0);
      return $this->getReflection()->invokeArgs($stack[0]['args']);
    }
```

Granted, this is pretty hacky (and limits the caller to "only" 10 by-ref arguments), but it gets the job done in about the only way I could figure out.

I didn't put it through as much testing as I probably should have, but what I did test is that:
a) It allows for references to be passed through properly (outside the known limitation of by-ref parameters needing to be explicitly listed).
b) By-val parameters are not actually passed by-ref if the closure itself does not expect them to be.
c) Actual parameter counts/requirements aren't impacted.

With the patch in place, the test code above outputs what we'd expect:
```
string 'new value!' (length=10)
string 'new value!' (length=10)
```

**Comment by jeremeamia** [comment]
Including [this text](https://github.com/jeremeamia/super_closure/blob/3dc8543da9e182f93ce8d8f115a27633a5d32fa1/src/SerializableClosure.php#L66-L68) in the `SerializableClosure` class to call out this known problem.

> Args passed-by-reference lose their references when proxied through `__invoke()`. This is is an unfortunate, but understandable, limitation of PHP that will probably never change.
