### ISSUE TITLE
1.x Is Not A Good Branch Name

### ISSUE THREAD

**Issue by GrahamCampbell** [jeremeamia/super_closure#29]
`1.x` means packagist is treating this as `1-dev`. Surely you want this to be treated as `1.0-dev`, so you need to name the branch `1.0.`.

**Comment by GrahamCampbell** [comment]
Also, I'd recommend either renaming `v2` to `2.0`, or renaming it to `master`, and adding a branch alias.

**Comment by jeremeamia** [comment]
Ah, good point. Will fix.

**Comment by GrahamCampbell** [comment]
Also, the `old` branch should be named `0.8`. :)

**Comment by GrahamCampbell** [comment]
You forgot to delete the `old` branch btw. :)

**Comment by GrahamCampbell** [comment]
Also, packagist is crap at dealing with branches: https://packagist.org/packages/jeremeamia/SuperClosure. You're going to need to manually delete the old branches from there. :/
