### ISSUE TITLE
2.0 Is Broken?

### ISSUE THREAD

**Issue by GrahamCampbell** [jeremeamia/super_closure#34]
![image](https://cloud.githubusercontent.com/assets/2829600/5807888/68c2fc1e-a01f-11e4-92b2-38afe6b8c6df.png)

This results in php saying serialization of a closure is not allowed.

**Comment by GrahamCampbell** [comment]
Related: https://github.com/laravel/framework/pull/7049.

**Comment by jeremeamia** [comment]
composer update? It working for me.

**Comment by GrahamCampbell** [comment]
Is your packagist hook working? Travis seems very confused. https://travis-ci.org/laravel/framework/jobs/47571123. It's trying to load an old commit.

**Comment by GrahamCampbell** [comment]
https://packagist.org/packages/jeremeamia/SuperClosure

**Comment by GrahamCampbell** [comment]
Yep - that's the issue. You need to delete all the old branches from github and then delete them from packagist too. They hit force update.

**Comment by GrahamCampbell** [comment]
The "old" branch still needs removing from github, and "2.x-dev" and "old-dev" from packagist.

**Comment by GrahamCampbell** [comment]
And "1.x-dev" needs removing too actually.

**Comment by jeremeamia** [comment]
How about now?

**Comment by GrahamCampbell** [comment]
Yeh. All working. https://travis-ci.org/laravel/framework/builds/47586571. Thanks. :)

**Comment by GrahamCampbell** [comment]
Is it time for `v2.0.0-alpha3`, `v2.0.0-beta1`, or indeed `v2.0.0-RC1` soon?
