### ISSUE TITLE
Breaking character in serialized closure

### ISSUE THREAD

**Issue by storeman** [jeremeamia/super_closure#36]
As of the beta of version 2, there is a breaking character in the serialized closure when I store it in the database. It's hard to track, but it broke my insert-query. Because of this the serialized string was partially stored in the db. Weird enough it didn't break my query.

If I look at the serialized closure in the browser, there are a few breaking characters which translate to the html-tag &#10;

I could base64 the code, that was a dirty workaround.

A part of the serialized string here:
```
....."serializer";O:23:"SuperClosure\Serializer":1:{s:33:"�SuperClosure\Serializer�analyzer";O:33:"SuperClosure\Analyzer\AstAnalyzer":....
```

**Comment by jeremeamia** [comment]
I believe you a running into an issue will null bytes. As explained in a note on the [PHP manual entry for `serialize()`](http://php.net/manual/en/function.serialize.php):

> Object's private members have the class name prepended to the member name; protected members have a '*' prepended to the member name. These prepended values have null bytes on either side.

SuperClosure has never done anything to prevent those null bytes from being included in the serialized string. For example, if you serialize a closure that has an object with private members as one of it's context variables, you would've hit the same problem with any version of SuperClosure. It's your responsibility to take the serialized data, and format it for the purpose of whatever you are doing with it. In your case, it sounds like doing a `base64_encode()` would be a good idea.

The latest beta of SuperClosure includes the Serializer object in the serialization, which does have private members, and would definitely output null bytes. That is why you are running into issues now. However, I've [just made a change](https://github.com/jeremeamia/super_closure/commit/3e3ba009b41eaa39f5e90c4622115a5b2ae5a3d4) that removes the need to serialize the Serializer. With that commit, the symptom of your problem should disappear, but your actual problem still remains.

**Comment by storeman** [comment]
That explains a lot. Thanks. I will definitely use base64 as this will prevent future issues in this area.
