### ISSUE TITLE
__debugInfo fails after unserialize()

### ISSUE THREAD

**Issue by assertchris** [jeremeamia/super_closure#44]
`SerializableClosure::serialize()` does not account for `SerializerInterface $serializer = null`, in the constructor. If this parameter isn't provided then the default serializer, which the constructor creates, is not created during `SerializableClosure::unserialize()`.

```
PHP Fatal error:  Call to a member function getData() on null in /[redacted]/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php on line 164
PHP Stack trace:
PHP   1. {main}() /[redacted]/debug.php:0
PHP   2. print_r() /[redacted]/debug.php:20
PHP   3. SuperClosure\SerializableClosure->__debugInfo() /[redacted]/debug.php:20

Fatal error: Call to a member function getData() on null in /[redacted]/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php on line 164

Call Stack:
    0.0003     230504   1. {main}() /[redacted]/debug.php:0
    0.0308    3387808   2. print_r() /[redacted]/debug.php:20
    0.0308    3388216   3. SuperClosure\SerializableClosure->__debugInfo() /[redacted]/debug.php:20
```

**Comment by travisulrich** [comment]
I also ran across this issue yesterday. `var_dump` works successfully on the serialized object, but `print_r` causes the error @assertchris mentioned above.

**Comment by Anahkiasen** [comment]
Small reproducible test case:

```php
$closure = function() {

};

$closure = new SerializableClosure($closure);
var_dump($closure); // Works

$closure = unserialize(serialize($closure));
var_dump($closure); // Crashes
```

**Comment by GrahamCampbell** [comment]
@Anahkiasen Surely `$closure = unserialize(serialize($closure))->getClosure();` is the correct usage here?

**Comment by jeremeamia** [comment]
Thanks for the bug report and repro code.

**Comment by Anahkiasen** [comment]
@GrahamCampbell Not that I know of no, the SerializableClosure wraps the closure and is still callable, it's more like a decorator
