### ISSUE TITLE
[Proposal] Add bindTo support

### ISSUE THREAD

**Issue by assertchris** [jeremeamia/super_closure#46]
Hey friend!

I'm trying to change the binding of the decorated `Closure`, with much difficulty. It's private, so a subclass of `SerializableClosure` wont work. Would you be open to be adding `bindTo` support?

**Comment by jeremeamia** [comment]
Possibly. Can you help me understand your use case a little more?

`SerializableClosure` does have a `getClosure()` method.

**Comment by jeremeamia** [comment]
Adding something like this could work, right?

```php
    public function bindTo($newthis, $newscope = 'static')
    {
        return new self(
            $this->closure->bindTo($newthis, $newscope),
            $this->serializer
        );
    }
```

**Comment by assertchris** [comment]
Yes, that is exactly what I was thinking!

It's not that it was impossible, but rather that I was repeating your
suggestion often...

**Comment by jeremeamia** [comment]
Does #47 look good?

**Comment by Ocramius** [comment]
I still don't get the use-case (same applies to #47)

**Comment by jeremeamia** [comment]
I think it's not strictly necessary, but If you look at `SerializableClosure` as Decorator of `Closure`, then adding `bindTo()` would complete the support of `Closure`'s "interface".

**Comment by Ocramius** [comment]
I'm still wondering about the use-case, as no code should ever be written
without it :-P

**Comment by assertchris** [comment]
The latest example of when I've needed to bind a SC to a new context:
[one](https://github.com/asyncphp/assistant/blob/ca2b76b63537f4ef960d7d1f8ef596a4196482ed/src/Adapter/Task.php#L33)...
[two](https://github.com/asyncphp/assistant/blob/ca2b76b63537f4ef960d7d1f8ef596a4196482ed/src/Adapter/Task.php#L61-L97)...
[three](https://github.com/asyncphp/assistant/blob/ca2b76b63537f4ef960d7d1f8ef596a4196482ed/src/Adapter/ZeroMQ/Client.php#L24-L35)...
[four](https://github.com/asyncphp/assistant/blob/ca2b76b63537f4ef960d7d1f8ef596a4196482ed/src/Adapter/ZeroMQ/Worker.php#L55-L71)

As I mentioned; I often need to repeat this pattern and would prefer to [reduce the knowledge consuming code has of the structure of a SC](http://en.wikipedia.org/wiki/Law_of_Demeter).

**Comment by Ocramius** [comment]
This adds a new responsibility to SC tho, while what you're looking for is
something (in your codebase) that applies re-binding. No biggie, just not a
fan of adding utility methods, especially instance methods.

**Comment by assertchris** [comment]
The SC is just a decorator around Closure, which already does this. SC doesn't proxy the functionality though.

**Comment by Ocramius** [comment]
It's an "envelope". Yeah, I guess treating this addition as a factory
method is kinda acceptable then :-P

**Comment by assertchris** [comment]
Fixed in https://github.com/jeremeamia/super_closure/pull/47
