### ISSUE TITLE
Serializing Anonymous Classes 

### ISSUE THREAD

**Issue by GrahamCampbell** [jeremeamia/super_closure#50]
It looks like Phil's RFC to add anonymous classes is going to make it into php 7.0. I wonder if it would be possible for super closure to serialize anonymous classes too? I haven't looked into the fine details, but I'm just throwing this out there as a cool idea. Any thoughts?

**Comment by Ocramius** [comment]
Since we have AST support in 7, it should be feasible, yep.

**Comment by jeremeamia** [comment]
They seem to already be serializable, akaik

**Comment by vladqa** [comment]
@jeremeamia, can you explain, how can I serialize anonymous class code?

**Comment by jeremeamia** [comment]
I was wrong when I posted [this](https://github.com/jeremeamia/super_closure/issues/50#issuecomment-103996984). However, serializing anonymous classes was never the intention of this library. I think I remember a discussion about what makes it particularly challenging, but now I can't find it. Without thinking about it in depth, I can't remember. AFAIK, it's not possible.

**Comment by GrahamCampbell** [comment]
Opening again so we can at least add a note to the readme. ;)
