### ISSUE TITLE
SuperClosure does not load php5 custom extensions

### ISSUE THREAD

**Issue by ddeath** [jeremeamia/super_closure#54]
Hi there I am using super_closure in Laravel4 and it looks like super_closure does not know my custom function in php5 installed via extension.

 PHP Fatal error:  Call to undefined function solve_simplex() in /var/www/my_site/vendor/jeremeamia/SuperClosure/src/Jeremeamia/SuperClosure/SerializableClosure.php(99) : eval()'d code on     line 2
    PHP Stack trace:
    PHP   1. {main}() /var/www/my_site/artisan:0
    PHP   2. Symfony\Component\Console\Application->run() /var/www/my_site/artisan:59
    PHP   3. Symfony\Component\Console\Application->doRun() /var/www/my_site/vendor/symfony/console/Symfony/Component/Console/Application.php:121
    PHP   4. Symfony\Component\Console\Application->doRunCommand() /var/www/my_site/vendor/symfony/console/Symfony/Component/Console/Application.php:191
    PHP   5. Illuminate\Console\Command->run() /var/www/my_site/vendor/symfony/console/Symfony/Component/Console/Application.php:887
    PHP   6. Symfony\Component\Console\Command\Command->run() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Console/Command.php:96
    PHP   7. Illuminate\Console\Command->execute() /var/www/my_site/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:241
    PHP   8. Illuminate\Queue\Console\WorkCommand->fire() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Console/Command.php:108
    PHP   9. Illuminate\Queue\Worker->pop() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/Console/WorkCommand.php:64
    PHP  10. Illuminate\Queue\Worker->process() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:71
    PHP  11. Illuminate\Queue\Jobs\BeanstalkdJob->fire() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/Worker.php:119
    PHP  12. Illuminate\Queue\Jobs\Job->resolveAndFire() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/Jobs/BeanstalkdJob.php:50
    PHP  13. IlluminateQueueClosure->fire() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/Jobs/Job.php:96
    PHP  14. Jeremeamia\SuperClosure\SerializableClosure->__invoke() /var/www/my_site/vendor/laravel/framework/src/Illuminate/Queue/IlluminateQueueClosure.php:16
    PHP  15. ReflectionFunction->invokeArgs() /var/www/my_site/vendor/jeremeamia/SuperClosure/src/Jeremeamia/SuperClosure/SerializableClosure.php:64
    PHP  16. Jeremeamia\SuperClosure\SerializableClosure::{closure:/var/www/my_site/vendor/jeremeamia/SuperClosure/src/Jeremeamia/SuperClosure/SerializableClosure.php(99) : eval()'d code:1-4}() /    var/www/my_site/vendor/jeremeamia/SuperClosure/src/Jeremeamia/SuperClosure/SerializableClosure.php:64
    {"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Call to undefined function solve_simplex()","file":"\/var\/www\/my_site\/vendor\/jeremeamia\/    SuperClosure\/src\/Jeremeamia\/SuperClosure\/SerializableClosure.php(99) : eval()'d code","line":2}}

if I use function solve_simplex() anywhere else in my code it is working. 

In closure function extension_loaded is returning that my extension is not loaded. I do not know why because it is inserted in php.ini on extension= line...
Thanks

**Comment by ddeath** [comment]
Sorry guys. I just solved that issue. The problem was that your code in laravel is invoking throught php artisan command what means that it is run on CLI and therefore my extension is not loaded. However if i run it like php -dextension=simplexSolver.so artisan ... then it is working.

**Comment by tallcoder** [comment]
I'm having the same issue in a homestead env ... and that's not working. Lib doesn't exist.
