### ISSUE TITLE
Ideas - Just thinking out loud

### ISSUE THREAD

**Issue by jeremeamia** [jeremeamia/super_closure#56]
- Take a look at [Opis\Closure](https://github.com/opis/closure)
  - Uses stream wrapper to load code instead of eval(), allows for multiple (un)serializations.
  - Compare Token Parser logic
- See if we can determine if a closure is static with code parsing, instead of with [this awful function](https://github.com/jeremeamia/super_closure/blob/master/src/Analyzer/ClosureAnalyzer.php#L56-L61)
- Next major version
  - See if we can get the token parser's feature up-to-par
  - Make PHP-Parser an optional dependency
  - Perhaps join projects with Opis\Closure

**Comment by GrahamCampbell** [comment]
> See if we can determine if a closure is static with code parsing, instead of with this awful function

LOL. That function just got worse in order to make it work on PHP 7.
