### ISSUE TITLE
Serialization of closure failed

### ISSUE THREAD

**Issue by lezhnev74** [jeremeamia/super_closure#57]
Get this message when trying to serialize example:
$serializer1 = new SuperClosure\Serializer(null, $yourSecretSigningKey);
$data = $serializer1->serialize(function () {echo "Hello!\n";});

```
PHP error:  Serialization of closure failed: The file containing the closure, "PATH_LARAVEL/vendor/psy/psysh/src/Psy/ExecutionLoop/Loop.php(76) : eval()'d code" did not exist. in PATH_LARAVEL/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php on line 93
```

Is it trying to write to file without a permission?

**Comment by jeremeamia** [comment]
Nope it's trying to read a file that is not a file. SuperClosure depends on being able to read the file that the code is contained it, because it needs to parse that code. This code seems to have originated from `eval()`, and is not in a file. There's not much I can do about that.

**Comment by lezhnev74** [comment]
Thanks, I'll try to resolve it myself.
