### ISSUE TITLE
Serialization of 'Generator' is not allowed

### ISSUE THREAD

**Issue by low-ghost** [jeremeamia/super_closure#59]
I get this error, obviously, while trying to serialize a generator instance. This might be a pretty rare use-case, but is there any support for serializing generators or a way around the issue? My source code is here https://github.com/low-ghost/PhpMultithread (subject to change), but the general idea is I'm using generators for coroutines that check conditions of external processes (allowing a hacked together multithreading). I can pass a serialized closure to be executed in the background, but if that closure itself should spawn a child-process, it would have to support generators.

Let me know if I can be more clear about something and no biggie if this is simply unsupported.

**Comment by jeremeamia** [comment]
I've experimented with a few things, but so far my impression is that it's not possible. I can find no way to, starting with a instance of `Generator`, get the function that produced the generator. You can't shoot what you can't see.

**Comment by low-ghost** [comment]
that makes sense. the more I thought about it the more impossible it sounded. Thanks for looking into it though!

**Comment by jeremeamia** [comment]
Might be possible in PHP 7: http://php.net/manual/en/class.reflectiongenerator.php

**Comment by GrahamCampbell** [comment]
Very cool. Maybe we should reopen this until one of us can properly investigate this?

**Comment by Ocramius** [comment]
From what I saw initially, this is not possible without a debugger being active, as it is not possible to keep the state of scope variables.

**Comment by GrahamCampbell** [comment]
Right. Thanks @Ocramius. :)
