### ISSUE TITLE
Congrats

### ISSUE THREAD

**Issue by lgalaz** [jeremeamia/super_closure#64]
Sorry, didn't know where else to leave the message and I was just about to get going but wanted to leave my comment since I thought it useful for the Readme. 

I think one of the most basic and common use cases for your "super closures" is refactoring out switch statements or multiple if/elses. This is easily done with polymorphism, but what about the associative arrays/hashmap solution? which is simpler, faster, easier to read, very common in functional world.

php would just force me to do this:

    $socialServiceMap = [
      'twitter' => function ($params) {
        return new TwitterSocialService($params);
      },
      'instagram' => function ($params) {
        return new InstagramSocialService($params);
      }
    ];

on the same method, so as to not require serialization.

**Comment by Ocramius** [comment]
What advantage would you be getting by serializing data here?

**Comment by lgalaz** [comment]
Well, in my precise example, nothing. 
Cause I was just going for the current refactor in my code that led me to the "closures-serialization, issue in PHP" (replace "switch(e) {case: case: default: } | if() esleif() elseif() else" with a "map".)  
But, passing on lamdas to maps is something very common that will very likely span out of a scope.  (Think, "composition over inheritance" Strategy, Decorator, Composite, Chain of responsibility... those kind of things)
So, wherever you have a collection, and want to map it in any way, iterate over it, group, map/reduce, or simply when the values for your keys will be known until run time. Then, there is also parallelism, extension methods, things like tail recursion, etc...

**Comment by Ocramius** [comment]
And... what does that have to do with superclosure?

**Comment by lgalaz** [comment]
Whatever.

Maybe you have not noticed that when passing args between functions, they must be serializable. 

I just wanted to mention something I thought useful and compliment you on your code. I regret trying to expose what I thought a very common use case.

**Comment by jeremeamia** [comment]
@Igalaz I'm glad you found it useful. I think what you are highlighting is similar to how some people have used SuperClosure to serialize things like Pimple containers.

**Comment by Ocramius** [comment]
> Maybe you have not noticed that when passing args between functions, they must be serializable. 

Eh, that's what I mean: they don't need to be (in the same address space and non-multithreaded contexts) :-|

**Comment by lgalaz** [comment]
I stated at the beginning that not having them in the same address space was a constraint.

any way. thats it for me.
