### ISSUE TITLE
email queue exception 'ErrorException' with message 'Undefined variable: event'

### ISSUE THREAD

**Issue by bemyguestmichael** [jeremeamia/super_closure#65]
I'm trying to do an email queue through an event handler and I'm getting exception **'ErrorException' with message 'Undefined variable: event' in /vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(153) : eval()'d code:2** below is the sample code

```
\Mail::queue(
			'emails.report_notification',
    	    [
    	    	'first_name'	=> $event->first_name,
    	    	'download_url'	=> $event->download_url,
    	    ],
    	
    	    function ($message) {
    	    	$message->subject( 'Report' );
    	    	$message->from(
    	    					'admin@test.com',
    	    					'admin'
    	    	);
    	    	$message->to( $event->email );
			}
		);
```

**Comment by GrahamCampbell** [comment]
Not a bug. Change `function ($message) {` to `function ($message) use ($event) {` :)

**Comment by GrahamCampbell** [comment]
If event is an object, you may even want to actually pass through just the email rather than the whole event.

**Comment by bemyguestmichael** [comment]
Oh I see. Thanks @GrahamCampbell
