### ISSUE TITLE
Release 2.2.0

### ISSUE THREAD

**Issue by GrahamCampbell** [jeremeamia/super_closure#72]
I think we're ready to release 2,2,0 now @jeremeamia. There are two things potentially stopping us though:

1. https://github.com/jeremeamia/super_closure/pull/53 might need reviewing first.
2. You might want to wait for the final PHP 7.0.0 release before we say that 2.2.0 is 100% PHP 7 compatible.

**Comment by jeremeamia** [comment]
Yeah, I need to review that one and finish my open PRs. Let's wait for the 7 stable release. That will hopefully give me time.

**Comment by GrahamCampbell** [comment]
Nice. The stable PHP release is just under 2 weeks away as far as I know.

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia.

**Comment by GrahamCampbell** [comment]
Ping @jeremeamia.

**Comment by GrahamCampbell** [comment]
I think we're ready now

**Comment by GrahamCampbell** [comment]
:ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship: :ship:

**Comment by jeremeamia** [comment]
Wahooooooooo!!!

**Comment by GrahamCampbell** [comment]
Oh, one tiny thing left...

**Comment by GrahamCampbell** [comment]
https://github.com/jeremeamia/super_closure/pull/79

**Comment by jeremeamia** [comment]
I gotta head to the airport in about an hour, but I'll write up the release notes and tag it once I get there. Alternatively, you may do this, if you like. I'll just want to review the release notes. I'll check back on this ticket in a couple of hours.

**Comment by GrahamCampbell** [comment]
Probably best to leave that to you.

> I gotta head to the airport in about an hour

Going anywhere nice?

**Comment by jeremeamia** [comment]
Home! :smile:

We just moved from Seattle, Washington (the rainy place), to Phoenix, Arizona (the sunny place). I flew back up to Seattle to supervise the movers getting everything loaded on the truck and run some _very_ last minute errands. Headed back to Arizona now, where I will live out the remainder of my days.

My wife and I are originally from there, so it's home for us, and is near both of our families.

**Comment by GrahamCampbell** [comment]
Awesome! Have fun. :)
