### ISSUE TITLE
self:: usage throws error when unserializing

### ISSUE THREAD

**Issue by jfsalzmann** [jeremeamia/super_closure#74]
I recently started using your Super Closure PHP module in our Yii 1.1 framework when implementing a worker queue. I got a problem there when I used self:: in the closures I want to serialize. In the moment the unserialized closure is called, I get a fatal PHP error:

> PHP Fatal error:  Call to undefined method SuperClosure\SerializableClosure::_sendNotifications() in ~~[...]~~/common/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(153) : eval()'d code on line 2

Let me provide some information: the closure passed looks like

``` php
        function($users) use ($push_notification,$item_id,$item_type,$link_type,$silent,$app_notification_id){
            self::_sendNotifications($users, $push_notification, $item_id, $item_type, $link_type, $silent, $app_notification_id);
        }
```

This is how I unserialize and run the closure:

``` php
$this->body = (new SuperClosure\Serializer())->unserialize($this->body['_payload']);
$this->exitCode = call_user_func_array($this->body, is_array($this->params) ? $this->params : array());
```

The serialized string contains the following:

```
C:32:"SuperClosure\SerializableClosure":1113:{a:5:{s:4:"code";s:234:"function ($users) use($push_notification, $item_id, $item_type, $link_type, $silent, $app_notification_id) { self::_sendNotifications($users, $push_notification, $item_id, $item_type, $link_type, $silent, $app_notification_id); };";s:7:"context";a:6:{s:17:"push_notification";O:16:"PushNotification":12:{s:11:"page_search";N;s:19:"CActiveRecord_new";b:0;s:26:"CActiveRecord_attributes";a:7:{s:6:"status";i:3;s:16:"is_category_text";i:0;s:4:"week";i:0;s:4:"text";s:19:"guest4 followed you";s:4:"date";s:19:"2015-11-27 11:16:39";s:16:"app_notification";s:3:"314";s:2:"id";s:3:"412";}s:23:"CActiveRecord_related";a:0:{}s:17:"CActiveRecord_c";N;s:18:"CActiveRecord_pk";s:3:"412";s:21:"CActiveRecord_alias";s:1:"t";s:15:"CModel_errors";a:0:{}s:19:"CModel_validators";N;s:17:"CModel_scenario";s:6:"update";s:14:"CComponent_e";N;s:14:"CComponent_m";N;}s:7:"item_id";s:1:"1";s:9:"item_type";s:4:"user";s:9:"link_type";s:12:"user_profile";s:6:"silent";b:1;s:19:"app_notification_id";s:3:"314";}s:7:"binding";N;s:5:"scope";s:23:"PushNotificationService";s:8:"isStatic";b:1;}}
```

I'm using the AstAnalyzer, but as I understood the documentation, it should actually work with both analyzers. I'm running on PHP 5.4.16.

[reported in my email to @jeremeamia on 11/27, copy here for tracking reasons]

**Comment by GrahamCampbell** [comment]
I think it's maybe best if you just call `$this->_sendNotifications`?

**Comment by GrahamCampbell** [comment]
At least for now.

**Comment by joffdd** [comment]
Thanks @GrahamCampbell, I hard coded the class name so it's working for me right now, but I think this is something which you may want to solve one day anyway.

**Comment by GrahamCampbell** [comment]
Agreed. ;)

**Comment by jeremeamia** [comment]
Yeah, I need to look into fixing this for sure.

**Comment by skovmand** [comment]
+1

I use a callback in Laravel 5.1 for attaching sender name and e-mail to the e-mails sent:

```
    /**
     * Wrapper around Mail::queue.
     *
     * @param $email
     * @param $title
     * @param $view
     * @param array $data
     */
    public function queueMail($email, $title, $view, array $data)
    {
        Mail::queue($view, $data, $this->setEmailParameters($email, $title));
    }
```


```
    /**
     * Return the callback which sets email-address and title.
     *
     * @param $recipientEmail
     * @param $title
     * @return callable
     */
    private function setEmailParameters($recipientEmail, $title)
    {
        return function($message) use ($recipientEmail, $title) {
            $message->to($recipientEmail)->subject($title);
            $message->from(self::fromEmail, self::fromName);
        };
    }
```

Recently all my queued jobs started failing with an error from ```vendor/jeremeamia/SuperClosure/src/SerializableClosure.php:210```. The exception message is ```Cannot access self:: when no class scope is active```. 

Changing the ```self::fromEmail``` to an instance variable, e.g. ```$this->fromEmail``` solves the problem and is okay for my use case.

**Comment by GrahamCampbell** [comment]
Alternatively, you could use a callable instead of a closure, and avoid this issue, I think...

**Comment by claar** [comment]
Same issue, this was really a pain to track down -- this issue began when I upgraded from 2.1.0 to 2.2.0.

**Comment by jeremeamia** [comment]
@jfsalzmann @skovmand @claar I'd like to fix this issue, but I cannot reproduce it. Can someone send a PR with a test case in [`/tests/Integ/SerializationTest.php`](https://github.com/jeremeamia/super_closure/blob/master/tests/Integ/SerializationTest.php) that causes a failure?

For example, I added the following test case (but it worked fine):

In `SerializationTest.php`:
```php
    public function testSerializeClosureWithSelf()
    {
        $closure = Selfie::getClosure();

        $results = $this->getResults($closure, []);
        $this->assertAllEquals(10, $results);
    }
```

And here is the test fixture, `Selfie.php`:
```php
<?php namespace SuperClosure\Test\Integ\Fixture;

class Selfie
{
    private static $value = 10;

    public static function getClosure()
    {
        return function () {
            return self::getValue();
        };
    }

    private static function getValue()
    {
        return self::$value;
    }
}
```

---

Also, could you possibly provide more context for your functions that are failing. For example, it woud be useful to know the following:

1. The code for entire function where the closure is declared (you all actually did provide this)
2. The name of the class where the closure is declared
3. The namespace that the class is in
4. Any use statements within the namespace
5. The string representation of the serialized closure
6. What PHP version you are using

---

It looks like @claar is having more luck with version 2.1, so please try that if you haven't already. I'll also review the differences in 2.1 and 2.2 and see if I find an issue. Some things did change in how the binding and scope are handled, but I didn't anticipate this issue as a result, nor can I currently reproduce it.

**Comment by jeremeamia** [comment]
This software is no longer maintained. Consider using [opis/closure](https://github.com/opis/closure) instead.
