### ISSUE TITLE
Namespace issue

### ISSUE THREAD

**Issue by jfsalzmann** [jeremeamia/super_closure#80]
Hello again, I'm unfortunately facing another issue. PHP 5.4.16, Yii Framework 1.1

```
PHP Error[2]: include(AppCheckInsController.php): failed to open stream: No such file or directory
    in file .../common/vendor/yiisoft/yii/framework/YiiBase.php at line 427
#0 .../common/vendor/yiisoft/yii/framework/YiiBase.php(427): autoload()
#1 unknown(0): autoload()
#2 unknown(0): spl_autoload_call()
#3 .../common/vendor/jeremeamia/SuperClosure/src/SerializableClosure.php(130): Closure->bindTo()
#4 unknown(0): SuperClosure\SerializableClosure->unserialize()
#5 .../common/vendor/jeremeamia/SuperClosure/src/Serializer.php(96): unserialize()
#6 .../common/components/MongoMQMessageWrapper.php(77): SuperClosure\Serializer->unserialize()
```

The namespace of the class from where the closure has been serialized is something like `\backend\controllers\AppCheckInsController` - looking how both AstAnalyzer and TokenAnalyzer are storing the binding information, this information is getting lost:

```
C:32:"SuperClosure\SerializableClosure":945:{a:5:{s:4:"code";s:56:"function () use($check_in) { $check_in->delete(); };";s:7:"context";a:1:{s:8:"check_in";O:10:"AppCheckIn":15:{s:10:"page_title";N;s:19:"neighbourhood_title";N;s:5:"email";N;s:9:"has_image";N;s:19:"CActiveRecord_new";b:0;s:26:"CActiveRecord_attributes";a:11:{s:2:"id";s:4:"1015";s:11:"app_user_id";s:1:"1";s:7:"page_id";N;s:12:"neighbour_id";s:1:"1";s:8:"datetime";s:19:"2015-11-03 13:03:34";s:4:"type";s:0:"";s:11:"description";s:43:"What the food fuck is this extra test hoot?";s:8:"question";s:1:"1";s:5:"image";N;s:5:"thumb";s:0:"";s:7:"deleted";i:1;}s:23:"CActiveRecord_related";a:0:{}s:17:"CActiveRecord_c";N;s:18:"CActiveRecord_pk";s:4:"1015";s:21:"CActiveRecord_alias";s:1:"t";s:15:"CModel_errors";a:0:{}s:19:"CModel_validators";N;s:17:"CModel_scenario";s:6:"update";s:14:"CComponent_e";N;s:14:"CComponent_m";N;}}s:7:"binding";N;s:5:"scope";s:21:"AppCheckInsController";s:8:"isStatic";b:0;}}
```

(essentially looking at this part:)

```
s:7:"binding";N;s:5:"scope";s:21:"AppCheckInsController";s:8:"isStatic";b:0;
```

Is there anything I'm handling wrong (or maybe the framework), or, in any case, do you think there is a workaround for that issue? Thank you.

**Comment by jeremeamia** [comment]
It seems from this error that the `AppCheckInsController` class is not autoload-able from the context where you are unserializing the closure.

Things to check:
- Is `AppCheckInsController` the right class name? Or is it supposed to have a namespace as well?
- Does it seem like `AppCheckInsController` should be able to be loaded from where you are unserializing the closure? You may need to do some investigating. There could be a framework issue, or at least an issue in how you are using the framework.

**Comment by jeremeamia** [comment]
@jfsalzmann Also, I apologize for not responding sooner. Holidays + new job + health problems = no time.

**Comment by jeremeamia** [comment]
Closing due to age
