### ISSUE TITLE
Error when using Zend Guard

### ISSUE THREAD

**Issue by kjmtrue** [jeremeamia/super_closure#83]
Hi,

I'm using Laravel and Zend Guard 7 to encode my project.

But I alway receiver error "Serialization of closure failed: The closure was not found within the abstract syntax tree."

Can you help me fix it.

Thank you.

**Comment by oriceon** [comment]
Have same issue but only in encoded files... Any ideea how to fix that? Thanks!

**Comment by jeremeamia** [comment]
SuperClosure is likely not compatible with Zend Guard. SuperClosure has to parse the source code in order to perform the serialization. If it's trying to read the encoded source, which I suspect it is, then it would fail.

**Comment by GrahamCampbell** [comment]
Yeh. I'd say this is a no-fix.

**Comment by oriceon** [comment]
Ok, thanks for answer. I`ve made a non-encoded helper-file.php that contain only one function that send mails and call that function in other encoded files. Works ok.

**Comment by jeremeamia** [comment]
Gotcha. That makes sense then. Thanks for letting us know. I should probably add this a FAQ in the readme or something.

**Comment by GrahamCampbell** [comment]
👍
