### ISSUE TITLE
Bug with EventEmitter?

### ISSUE THREAD

**Issue by cursedcoder** [jeremeamia/super_closure#85]
Hi,

see this gist https://gist.github.com/cursedcoder/b1c3c1d90e4f81eaf36a4a1b1c3831ba

`Serialization of closure failed: Serialization of 'Closure' is not allowed`

**Comment by GrahamCampbell** [comment]
You need to actually serialize the closure itself, not just an object with a closure as a property? Does that make sense?

**Comment by cursedcoder** [comment]
I would like to serialize object and its closures actually

**Comment by GrahamCampbell** [comment]
Right, well you'd need to make some code yourself that walked down the properties and serialize them with super closure. We don't do that automatically. We only serialize actual closures as an input.

**Comment by cursedcoder** [comment]
Makes sense.
