### ISSUE TITLE
Cannot instantiate interface PhpParser\Parser

### ISSUE THREAD

**Issue by divostar** [jeremeamia/super_closure#86]
Hello Jeremeamia, I notice an issue with version 2.2.0 of your project. The function below wouldn't work 

```
private function getFileAst(\ReflectionFunction $reflection)
    {
        $fileName = $reflection->getFileName();
        if (!file_exists($fileName)) {
            throw new ClosureAnalysisException(
                "The file containing the closure, \"{$fileName}\" did not exist."
            );
        }


        return $this->getParser()->parse(file_get_contents($fileName)); // This line doesn't work
    }
```
With version v2.1.0  of nikic/php-parser, Parser is no longer a class but an interface and so it cannot be instantiated. We now have `class Multiple implements Parser {     }`. 

For a work around, either do a 

1. `use PhpParser\Parser\Multiple as CodeParser;`
or
2. Bind the Parser interface to the concrete class Multiple so that it can be instantiated. 

I am sure you forgot to make that change. With older versions of nickic/php-parser, Parser was a concrete class. Thanks

**Comment by jeremeamia** [comment]
Thanks. I'll take a look at it when I have time. That may be a couple months from now though, so feel free to send a PR if you have time.

**Comment by divostar** [comment]
Okay

**Comment by GrahamCampbell** [comment]
We can just do the same as what class preloader has done?

**Comment by GrahamCampbell** [comment]
Wait, our code already does this. How come this is nor working for you. That code never gets called on 2.x?

**Comment by GrahamCampbell** [comment]
Our code looks like this:

```php

    /**
     * @param \ReflectionFunction $reflection
     *
     * @throws ClosureAnalysisException
     *
     * @return \PhpParser\Node[]
     */
    private function getFileAst(\ReflectionFunction $reflection)
    {
        $fileName = $reflection->getFileName();
        if (!file_exists($fileName)) {
            throw new ClosureAnalysisException(
                "The file containing the closure, \"{$fileName}\" did not exist."
            );
        }


        return $this->getParser()->parse(file_get_contents($fileName));
    }

    /**
     * @return CodeParser
     */
    private function getParser()
    {
        if (class_exists('PhpParser\ParserFactory')) {
            return (new ParserFactory)->create(ParserFactory::PREFER_PHP7);
        }

        return new CodeParser(new EmulativeLexer);
    }
```

The bottom line is only ever called on php parser 1.x.

**Comment by GrahamCampbell** [comment]
Are you noticing this issue due to a static analzyer, or due to it actually happening?

**Comment by divostar** [comment]
I am experiencing the issue with nikic/php-parser v2.1.0 and jeremeamia/SuperClosure 2.2.0 on my production server but not on my development server (which is weird).  For a quick fix in my production server, I had to use v1.4.1 of php parser. Out of curiosity, I tested SuperClosure 2.2.0 and php-parser v2.1.0 on another project on thesame production server and wasn't getting the exception. When I open your code in PhpStorm, I notice that the bottom line is underlined with 
the error "Cannot Instantiate Interface Parser" thesame exception that was displayed when I was using nikic/php-parser v2.1.0 and jeremeamia/SuperClosure 2.2.0 on the prod server.

**Comment by GrahamCampbell** [comment]
DId you restart/reload php-fpm after deploying?

**Comment by GrahamCampbell** [comment]
It looks like you just have stale caches on the productyion server.

**Comment by divostar** [comment]
Let me reload and see what I get.
