### ISSUE TITLE
PHP5: Cannot bind an instance to a static closure

### ISSUE THREAD

**Issue by storeman** [jeremeamia/super_closure#88]
When serializing anonymous functions, PHP throws an exception:
"Cannot bind an instance to a static closure"

This is a PHP error in the ClosureAnalyzer::isClosureStatic::58 and is caused by this line:

`$closure = @$closure->bindTo(new \stdClass);`

By removing this line and the following 4. The problem is resolved.

In PHP7, this is not an issue by the way, so a version check could be useful. It's also not possible to catch the exception.

**Comment by jeremeamia** [comment]
See discussions on #89 for the root cause.
